export const FETCH_FOODS = 'FETCH_FOODS';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const API_ERROR = 'API_ERROR';
