# Generated by Django 3.1.4 on 2020-12-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('imageUrl', models.CharField(max_length=200, verbose_name='Image Url')),
                ('price', models.CharField(max_length=50, verbose_name='price')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category', verbose_name='category Id')),
            ],
            options={
                'verbose_name': 'Food_Item',
                'verbose_name_plural': 'Food_Items',
            },
        ),
    ]
